pipeline {
    
    agent any 

    stages{

        stage("Git checkout"){

            steps{

                git branch: 'main', url: 'https://github.com/Emmylong1/TalentPlus-Project1.git'
            }
        }
         stage("UNIT Testing"){
            
            steps{

                sh "mvn test"

            }
        }
    }
}